import { useEffect, useState } from "react";
import { InternalIntro } from "../components/InternalIntro";
import { useConsent } from "../components/ConsentManager";
import { consentServices } from "../lib/consent";
import { siteConfig } from "../config";

export function PreferencesPage() {
  const { consent, save } = useConsent();
  const [analytics, setAnalytics] = useState(consent?.analytics ?? false);
  const [saved, setSaved] = useState(false);
  useEffect(() => setAnalytics(consent?.analytics ?? false), [consent]);
  const choose = (value: boolean) => { setAnalytics(value); save(value); setSaved(true); };
  return <main id="contenuto" className="internal-main preferences-page"><InternalIntro index="L / 02" eyebrow="PREFERENZE COOKIE" title="La scelta resta tua." copy="Gli strumenti necessari mantengono operativo il sito. Gli analitici restano disattivati finché non scegli esplicitamente di abilitarli." /><section className="preferences-panel" aria-labelledby="controls-title"><div className="preferences-status"><p className="eyebrow">STATO ATTUALE</p><p>{consent ? <>Decisione registrata il <strong>{new Intl.DateTimeFormat("it-IT", { dateStyle: "long" }).format(new Date(consent.decidedAt))}</strong>. Versione informativa: <strong>{consent.version}</strong>.</> : <>Nessuna scelta ancora registrata. Gli analitici sono disattivati.</>}</p></div><h2 id="controls-title">Controlli</h2><div className="preference-row"><div><strong>Necessari</strong><p>Sicurezza del modulo e memoria della scelta.</p></div><span className="always-on">Sempre attivi</span></div><label className="preference-row preference-control"><div><strong>Analitici</strong><p>Google Analytics 4 per statistiche aggregate, senza pubblicità.</p></div><input type="checkbox" checked={analytics} onChange={(event) => { setSaved(false); setAnalytics(event.target.checked); }} /></label><div className="preference-actions"><button type="button" className="button button-equal" onClick={() => choose(analytics)}>Salva preferenze</button><button type="button" className="button button-equal" onClick={() => choose(false)}>Rifiuta non necessari</button><button type="button" className="button button-equal" onClick={() => choose(true)}>Accetta tutti</button></div><p className="preferences-feedback" role="status" aria-live="polite">{saved ? "Preferenze salvate. La modifica è attiva da ora." : ""}</p></section><section className="storage-section" aria-labelledby="storage-title"><p className="eyebrow">SERVIZI E MEMORIE</p><h2 id="storage-title">Cosa può essere utilizzato.</h2><div className="table-wrap" tabIndex={0} role="region" aria-label="Tabella di servizi e memorie, scorribile orizzontalmente"><table><thead><tr><th>Categoria</th><th>Servizio</th><th>Memoria</th><th>Durata</th><th>Scopo</th></tr></thead><tbody>{consentServices.map((service) => <tr key={`${service.service}-${service.storage}`}><td>{service.category}</td><td>{service.service}</td><td><code>{service.storage}</code></td><td>{service.duration}</td><td>{service.purpose}</td></tr>)}</tbody></table></div><p>Versione corrente: <strong>{siteConfig.consentVersion}</strong>. La scelta scade dopo {siteConfig.consentLifetimeDays} giorni o prima in caso di modifiche sostanziali.</p><p><a href="/privacy/">Leggi l’informativa privacy completa</a>.</p></section></main>;
}
