import { InternalIntro } from "../components/InternalIntro";
import { siteConfig } from "../config";

export function PrivacyPage() {
  return <main id="contenuto" className="internal-main legal-page"><InternalIntro index="L / 01" eyebrow="INFORMATIVA PRIVACY" title="Dati, finalità e controllo." copy="Informazioni sul trattamento dei dati personali durante la navigazione e l’uso del modulo di contatto di miniutti.it." /><article className="legal-copy"><div className="legal-notice"><strong>Ultimo aggiornamento: 8 settembre 2026</strong><p>Questo testo descrive l’implementazione attuale e non sostituisce una verifica legale professionale.</p></div><nav className="legal-index" aria-label="Indice dell’informativa"><a href="#titolare">Titolare</a><a href="#dati">Dati trattati</a><a href="#servizi">Fornitori</a><a href="#cookie">Cookie e analitici</a><a href="#diritti">Diritti</a></nav>
  <section id="titolare"><h2>1. Titolare del trattamento</h2><p>Il titolare del trattamento è <strong>Tobia Miniutti</strong>, Bologna, Italia. Per richieste sulla protezione dei dati o per esercitare i diritti descritti in questa informativa: <a href={`mailto:${siteConfig.privacyEmail}`}>{siteConfig.privacyEmail}</a> oppure <a href={`tel:${siteConfig.landlineTel}`}>{siteConfig.landlineDisplay}</a>.</p><p>Le risposte possono provenire da <strong>{siteConfig.email}</strong>; eventuali integrazioni relative a una richiesta privacy devono essere inviate all’indirizzo dedicato. Non è stato designato un Responsabile della protezione dei dati, non ricorrendone attualmente i presupposti.</p></section>
  <section><h2>2. Ambito</h2><p>L’informativa si applica a miniutti.it, alla navigazione, alle preferenze di consenso e al modulo di contatto. Non si applica ai siti di terzi raggiungibili tramite collegamenti esterni.</p></section>
  <section id="dati"><h2>3. Categorie di dati trattati</h2><h3>3.1 Navigazione e sicurezza</h3><p>I servizi necessari alla pubblicazione e protezione del sito possono acquisire indirizzo IP, data e ora, risorsa richiesta, metodo, protocollo, codice di risposta, browser, sistema operativo, dispositivo, informazioni tecniche sulla connessione e identificativi della richiesta. GitHub Pages pubblica il sito statico; Cloudflare può operare come proxy e gestisce il Worker del modulo.</p><h3>3.2 Modulo di contatto</h3><p>Il modulo raccoglie nome e cognome, email, organizzazione facoltativa, categoria della richiesta, messaggio e attestazione di presa visione dell’informativa. I campi obbligatori sono necessari per l’inoltro. La presa visione <strong>non costituisce consenso</strong> a finalità analitiche.</p><p>Non inserire password, dati sanitari o altre informazioni sensibili non necessarie.</p><h3>3.3 Protezione anti-abuso</h3><p>Cloudflare Turnstile, il Worker e i limiti di invio possono trattare IP, dati tecnici, esito della verifica, identificativi della richiesta, contatori temporanei e codici diagnostici. I log del Worker minimizzano i dati e non registrano contenuto del messaggio, token o email; possono includere un identificativo tecnico, esito, tentativo e codice di errore.</p></section>
  <section><h2>4. Finalità e basi giuridiche</h2><h3>4.1 Erogazione e sicurezza</h3><p>I dati tecnici sono trattati per rendere disponibile il sito, diagnosticare problemi e prevenire spam o abusi sulla base del legittimo interesse del titolare, articolo 6(1)(f) GDPR.</p><h3>4.2 Gestione delle richieste</h3><p>I dati inviati servono a classificare la richiesta, inviare la conferma, ricontattare l’interessato e gestire la corrispondenza. La base giuridica è l’esecuzione di misure precontrattuali richieste dall’interessato, articolo 6(1)(b), oppure il legittimo interesse a rispondere alle comunicazioni spontanee, articolo 6(1)(f).</p><h3>4.3 Analisi delle visite</h3><p>Google Analytics 4 viene attivato soltanto dopo una scelta positiva. La base giuridica è il consenso, articolo 6(1)(a) GDPR e articolo 122 del Codice Privacy. Il consenso può essere revocato in qualsiasi momento senza conseguenze sull’uso del sito.</p></section>
  <section><h2>5. Flusso del contatto</h2><ol><li>Turnstile verifica l’invio;</li><li>il Worker applica schema, origine, hostname, azione e limiti;</li><li>i dati validi sono inoltrati a Make;</li><li>Make utilizza Zoho Mail per le comunicazioni previste;</li><li>il titolare riceve la richiesta e l’utente una conferma tecnica.</li></ol><p>La conferma non costituisce accettazione di proposte né assunzione di obblighi.</p></section>
  <section><h2>6. Modalità e misure</h2><p>Il trattamento avviene con strumenti informatici secondo i principi di minimizzazione, limitazione, integrità e riservatezza. Sono applicati cifratura in transito, limitazione degli accessi, verifica anti-abuso, rate limiting, controlli server-side e log tecnici minimizzati.</p></section>
  <section id="servizi"><h2>7. Destinatari e fornitori</h2><ul><li><strong>Cloudflare</strong>: proxy, Turnstile, Worker, rate limiting e log tecnici;</li><li><strong>GitHub</strong>: hosting statico tramite GitHub Pages;</li><li><strong>Make (Celonis)</strong>: automazione e inoltro delle richieste;</li><li><strong>Zoho Mail</strong>: invio, ricezione e conservazione della corrispondenza;</li><li><strong>Amazon CloudFront</strong>: distribuzione del video editoriale; la richiesta può trasmettere IP e dati tecnici;</li><li><strong>Google</strong>: Google Analytics 4, esclusivamente dopo consenso.</li></ul><p>I caratteri Instrument Serif, Outfit e Inter sono distribuiti con il sito e non richiedono connessioni a Google Fonts. I dati non sono venduti né usati per pubblicità o newsletter.</p></section>
  <section><h2>8. Trasferimenti internazionali</h2><p>L’uso di fornitori internazionali può comportare trattamento fuori dallo Spazio economico europeo. Quando applicabile, i trasferimenti si basano su decisioni di adeguatezza, Data Privacy Framework UE-USA per soggetti validamente certificati, clausole contrattuali standard o altro strumento previsto dagli articoli 45 e seguenti del GDPR. Informazioni sulle garanzie possono essere richieste al recapito privacy.</p></section>
  <section><h2>9. Conservazione</h2><ul><li><strong>richieste e corrispondenza:</strong> per il tempo necessario e, di norma, non oltre 12 mesi dalla conclusione del contatto;</li><li><strong>cronologia Make:</strong> 30 giorni secondo la configurazione dichiarata;</li><li><strong>log Worker:</strong> secondo la configurazione tecnica del servizio, limitatamente a sicurezza e diagnosi;</li><li><strong>rate limiting:</strong> per il periodo strettamente necessario al limite temporaneo;</li><li><strong>Zoho Mail:</strong> secondo la gestione della richiesta e il limite ordinario di 12 mesi, salvo cestino, recupero tecnico o obblighi;</li><li><strong>consenso locale:</strong> massimo 180 giorni;</li><li><strong>Google Analytics 4:</strong> {siteConfig.gaDataRetention}; l’attivazione in produzione richiede che questo valore sia verificato e documentato.</li></ul></section>
  <section id="cookie"><h2>10. Cookie, memoria tecnica e Google Analytics</h2><p>Il sito conserva in <code>localStorage</code> una registrazione minima della scelta: versione della policy, stato degli analitici, data della decisione e scadenza. È necessaria per non riproporre il pannello a ogni pagina e scade entro sei mesi.</p><p>Prima del consenso il tag Google non viene caricato e non vengono inviati ping senza cookie. Dopo consenso viene caricato una sola volta Google Analytics 4, senza Google Ads, remarketing, User-ID, Google Signals o personalizzazione pubblicitaria. Alla revoca il sito interrompe nuovi eventi e tenta di eliminare i cookie GA raggiungibili; i dati già trasmessi non possono essere richiamati dal browser.</p><p>Turnstile è una misura necessaria attivata soltanto nella sezione di contatto e non dipende dalla scelta sugli analitici. Il video editoriale è caricato da CloudFront; con “Riduci movimento” o “Risparmio dati” viene mostrata un’immagine locale senza riproduzione automatica.</p><p><a href="/preferenze-cookie/">Consulta o modifica le preferenze cookie</a>.</p></section>
  <section><h2>11. Decisioni automatizzate</h2><p>Non vengono effettuate profilazione o decisioni automatizzate con effetti giuridici. I sistemi anti-abuso possono bloccare automaticamente invii anomali o non validi esclusivamente per proteggere il modulo.</p></section>
  <section id="diritti"><h2>12. Diritti dell’interessato</h2><p>Nei casi previsti dagli articoli 15–22 GDPR puoi chiedere accesso, rettifica, cancellazione, limitazione, portabilità, opposizione e le tutele sulle decisioni automatizzate. Puoi inoltre revocare il consenso agli analitici dalla pagina delle preferenze.</p><p>Le richieste sono gratuite e possono essere inviate a <a href={`mailto:${siteConfig.privacyEmail}`}>{siteConfig.privacyEmail}</a>. Potranno essere richieste informazioni ragionevoli per verificare l’identità. Il riscontro avviene senza ingiustificato ritardo e, di norma, entro un mese, prorogabile nei casi previsti dal GDPR.</p></section>
  <section><h2>13. Reclamo</h2><p>È possibile proporre reclamo al <a href="https://www.garanteprivacy.it/" target="_blank" rel="noopener noreferrer">Garante per la protezione dei dati personali</a> o all’autorità competente nello Stato membro di residenza, lavoro o della presunta violazione.</p></section>
  <section><h2>14. Riferimenti ufficiali</h2><ul><li><a href="https://www.garanteprivacy.it/home/docweb/-/docweb-display/docweb/9677876" target="_blank" rel="noopener noreferrer">Linee guida cookie e altri strumenti di tracciamento — Garante Privacy</a>;</li><li><a href="https://www.edpb.europa.eu/documents/guideline/guidelines-052020-on-consent-under-regulation-2016679_en" target="_blank" rel="noopener noreferrer">EDPB Guidelines 05/2020 sul consenso</a>;</li><li><a href="https://eur-lex.europa.eu/eli/reg/2016/679/oj" target="_blank" rel="noopener noreferrer">Regolamento (UE) 2016/679</a>;</li><li><a href="https://developers.google.com/tag-platform/security/guides/consent" target="_blank" rel="noopener noreferrer">Documentazione Google sul consenso</a>.</li></ul></section><section><h2>15. Modifiche</h2><p>La pagina viene aggiornata quando cambiano aspetti normativi, tecnici o organizzativi. Una modifica sostanziale a finalità o fornitori invalida la scelta precedente e richiede una nuova decisione.</p></section></article></main>;
}
